# Exercise 3

<img src="https://img.itch.zone/aW1nLzM0MzUxOTUuanBn/original/FuMxog.jpg" />

In this exercise, you will perform EDA on the popular Pokémon dataset, which contains detailed information about hundreds of Pokémon, including their stats, types, generation, and whether they are legendary.

The Pokémon dataset is ideal for practicing EDA because it includes a mix of numerical features (such as Attack, Defense, Speed, HP) and categorical features (such as Type 1, Type 2, and Generation). This combination allows you to apply a wide range of EDA techniques, including summary statistics, data visualizations, grouping and aggregation, correlation analysis, and comparisons across categories.

Throughout the exercise, you will explore questions such as:
- Which Pokémon tend to have the highest or lowest stats?
- How do different Pokémon types compare in terms of strength or defense?
- Do Legendary Pokémon differ significantly from non-Legendary ones?
- How are various stats distributed across the entire dataset?
- Are there relationships or trade-offs between certain attributes (e.g., Attack vs. Defense)?

In [1]:
import kagglehub
import os
import pandas as pd

In [2]:
# Download latest version
path = kagglehub.dataset_download("abcsds/pokemon")
print("Path to dataset files:", path)

Using Colab cache for faster access to the 'pokemon' dataset.
Path to dataset files: /kaggle/input/pokemon

In [3]:
if os.path.isdir(path):
  print(True)

contents = os.listdir(path)
contents

mydataset = path + "/" + contents[0]
mydataset


df = pd.read_csv(mydataset)

True


## 1: Data Understanding (4 pts)

1. Display the first 10 rows.

In [41]:
# put your answer here
df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

2. Show dataset shape.

In [42]:
# put your answer here
df.shape

(800, 13)

3. Show all columns and its data types.

In [45]:
# put your answer here
df.dtypes

#              int64
Name          object
Type 1        object
Type 2        object
Total          int64
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

4. Identify which columns contain missing values.

In [50]:
# put your answer here
df.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

## 2. Summary Statistics (4 pts)

1. Generate `df.describe()`.

In [51]:
# put your answer here
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

2. Get mean, median, and mode of Attack.

In [61]:
# put your answer here
print('Mean:', df['Attack'].mean())
print('Median:', df['Attack'].median())
print('Mode:', df['Attack'].mode())

Mean: 79.00125
Median: 75.0
Mode: 0    100
Name: Attack, dtype: int64

3. Compute 25th and 75th percentiles for HP.

In [60]:
# put your answer here
print('25th:', df['HP'].quantile(0.25))
print('85th: ', df['HP'].quantile(0.75))

25th: 50.0
85th:  80.0

4. Compute standard deviation and variance of Speed.

In [63]:
# put your answer here
print('Standard Deviation: ', df['Speed'].std())
print('Variance: ', df['Speed'].var())

Standard Deviation:  29.06047371716149
Variance:  844.5111326658338

## 3. Filtering & Selection `(7 pts)`

Select all Pokémon with Attack > 100.

In [66]:
# put your answer here
filtered_df = df.filter(items=['Name', 'Attack'])
filtered_df[filtered_df['Attack'] > 100]

                          Name  Attack
7    CharizardMega Charizard X     130
8    CharizardMega Charizard Y     104
12     BlastoiseMega Blastoise     103
19       BeedrillMega Beedrill     150
39                    Nidoking     102
..                         ...     ...
793                    Yveltal     131
796        DiancieMega Diancie     160
797        HoopaHoopa Confined     110
798         HoopaHoopa Unbound     160
799                  Volcanion     110

[170 rows x 2 columns]

Select all Pokémon whose primary type (Type 1) is "Fire".

In [68]:
# put your answer here
filtered_df = df.filter(items=['Name', 'Type 1'])
filtered_df[filtered_df['Type 1'] == 'Fire']

                          Name Type 1
4                   Charmander   Fire
5                   Charmeleon   Fire
6                    Charizard   Fire
7    CharizardMega Charizard X   Fire
8    CharizardMega Charizard Y   Fire
42                      Vulpix   Fire
43                   Ninetales   Fire
63                   Growlithe   Fire
64                    Arcanine   Fire
83                      Ponyta   Fire
84                    Rapidash   Fire
135                     Magmar   Fire
147                    Flareon   Fire
158                    Moltres   Fire
169                  Cyndaquil   Fire
170                    Quilava   Fire
171                 Typhlosion   Fire
236                     Slugma   Fire
237                   Magcargo   Fire
259                      Magby   Fire
263                      Entei   Fire
270                      Ho-oh   Fire
276                    Torchic   Fire
277                  Combusken   Fire
278                   Blaziken   Fire
279      BlazikenMega Blaziken   Fire
352                      Numel   Fire
353                   Camerupt   Fire
354      CameruptMega Camerupt   Fire
355                    Torkoal   Fire
435                   Chimchar   Fire
436                   Monferno   Fire
437                  Infernape   Fire
518                  Magmortar   Fire
542                    Heatran   Fire
557                      Tepig   Fire
558                    Pignite   Fire
559                     Emboar   Fire
572                    Pansear   Fire
573                   Simisear   Fire
614                   Darumaka   Fire
615    DarmanitanStandard Mode   Fire
616         DarmanitanZen Mode   Fire
692                    Heatmor   Fire
721                   Fennekin   Fire
722                    Braixen   Fire
723                    Delphox   Fire
730                Fletchinder   Fire
731                 Talonflame   Fire
735                     Litleo   Fire
736                     Pyroar   Fire
799                  Volcanion   Fire

Select all Pokémon that are Legendary.

In [70]:
# put your answer here
filtered_df = df.filter(items=['Name', 'Legendary'])
filtered_df[filtered_df['Legendary'] == True]

                    Name  Legendary
156             Articuno       True
157               Zapdos       True
158              Moltres       True
162               Mewtwo       True
163  MewtwoMega Mewtwo X       True
..                   ...        ...
795              Diancie       True
796  DiancieMega Diancie       True
797  HoopaHoopa Confined       True
798   HoopaHoopa Unbound       True
799            Volcanion       True

[65 rows x 2 columns]

Select all Pokémon that are Generation 1 AND Legendary.

In [71]:
# put your answer here
filtered_df = df.filter(items=['Name', 'Generation', 'Legendary'])
filtered_df[(filtered_df['Generation'] == 1) & (filtered_df['Legendary'] == True)]

                    Name  Generation  Legendary
156             Articuno           1       True
157               Zapdos           1       True
158              Moltres           1       True
162               Mewtwo           1       True
163  MewtwoMega Mewtwo X           1       True
164  MewtwoMega Mewtwo Y           1       True

Select all Pokémon that are Water type OR Grass type.

In [72]:
# put your answer here
filtered_df = df.filter(items=['Name', 'Type 1'])
filtered_df[(filtered_df['Type 1'] == 'Water') | (filtered_df['Type 1'] == 'Grass')]

                      Name Type 1
0                Bulbasaur  Grass
1                  Ivysaur  Grass
2                 Venusaur  Grass
3    VenusaurMega Venusaur  Grass
9                 Squirtle  Water
..                     ...    ...
726               Greninja  Water
740                 Skiddo  Grass
741                 Gogoat  Grass
762              Clauncher  Water
763              Clawitzer  Water

[182 rows x 2 columns]

Select all Pokémon that are Fire type AND Attack > 120.

In [73]:
# put your answer here
filtered_df = df.filter(items=['Name', 'Type 1', 'Attack'])
filtered_df[(filtered_df['Type 1'] == 'Fire') & (filtered_df['Attack'] > 120)]

                          Name Type 1  Attack
7    CharizardMega Charizard X   Fire     130
147                    Flareon   Fire     130
270                      Ho-oh   Fire     130
279      BlazikenMega Blaziken   Fire     160
559                     Emboar   Fire     123
615    DarmanitanStandard Mode   Fire     140

Select all Pokémon whose type is in this list:
`["Dragon", "Ghost", "Dark"]`.

In [74]:
# put your answer here
filtered_df = df.filter(items=['Name', 'Type 1'])
filtered_df[filtered_df['Type 1'].isin(["Dragon", "Ghost", "Dark"])]

                    Name  Type 1
99                Gastly   Ghost
100              Haunter   Ghost
101               Gengar   Ghost
102    GengarMega Gengar   Ghost
159              Dratini  Dragon
..                   ...     ...
785  GourgeistSmall Size   Ghost
786  GourgeistLarge Size   Ghost
787  GourgeistSuper Size   Ghost
793              Yveltal    Dark
794     Zygarde50% Forme  Dragon

[95 rows x 2 columns]

## 4. Categorical Exploration `(9 pts)`

Find the number of Pokémon per primary type.

In [75]:
# put your answer here
df['Type 1'].value_counts()

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Ground       32
Ghost        32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

Find the number of Pokémon per generation.

In [76]:
# put your answer here
df['Generation'].value_counts()

Generation
1    166
5    165
3    160
4    121
2    106
6     82
Name: count, dtype: int64

Which type appears the most? Which appears the least?

In [147]:
# put your answer here
type_1 = df['Type 1'].value_counts()
type_2 = df['Type 2'].value_counts()

sum = type_1 + type_2

print(sum.nlargest(1))
print(sum.nsmallest(1))

Water    126
Name: count, dtype: int64
Ice    38
Name: count, dtype: int64

How many unique secondary types (Type 1) exist?

In [77]:
# put your answer here
df['Type 1'].nunique()

18

How many unique secondary types (Type 2) exist?

In [78]:
# put your answer here
df['Type 2'].nunique()

18


Which primary types have the most dual-type combinations?

In [126]:
 # put your answer here
 df.groupby('Type 1')['Type 2'].count().sort_values(ascending=False).head(1)

Type 1
Water    53
Name: Type 2, dtype: int64

Which type has the highest mean Attack?

In [79]:
# put your answer here
df.groupby('Type 1')['Attack'].mean().sort_values(ascending=False).head(1)

Type 1
Dragon    112.125
Name: Attack, dtype: float64

Which type has the lowest mean Defense?

In [80]:
# put your answer here
df.groupby('Type 1')['Attack'].mean().sort_values(ascending=True).head(1)

Type 1
Fairy    61.529412
Name: Attack, dtype: float64


Which generation has the highest average Speed?

In [81]:
# put your answer here
df.groupby('Generation')['Speed'].mean().sort_values(ascending=False).head(1)

Generation
1    72.584337
Name: Speed, dtype: float64

## 5. Groupby & Aggregation `(13 pts)`

Compute the average Attack per primary type.

In [82]:
# put your answer here
df.groupby('Type 1')['Attack'].mean().sort_values(ascending=False)

Type 1
Dragon      112.125000
Fighting     96.777778
Ground       95.750000
Rock         92.863636
Steel        92.703704
Dark         88.387097
Fire         84.769231
Flying       78.750000
Poison       74.678571
Water        74.151786
Ghost        73.781250
Normal       73.469388
Grass        73.214286
Ice          72.750000
Psychic      71.456140
Bug          70.971014
Electric     69.090909
Fairy        61.529412
Name: Attack, dtype: float64

Compute the maximum HP per generation.

In [83]:
# put your answer here
df.groupby('Generation')['HP'].max().sort_values(ascending=False)

Generation
2    255
1    250
3    170
5    165
4    150
6    126
Name: HP, dtype: int64

Compute the total number of Pokémon per primary type.

In [85]:
# put your answer here
df['Type 1'].value_counts()

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Ground       32
Ghost        32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

For each type, compute:

- mean Attack

- mean Defense

- mean Speed

In [86]:
# put your answer here
df.pivot_table(index=['Type 1'], values=['Attack', 'Defense', 'Speed'], aggfunc='mean')

              Attack     Defense       Speed
Type 1
Bug        70.971014   70.724638   61.681159
Dark       88.387097   70.225806   76.161290
Dragon    112.125000   86.375000   83.031250
Electric   69.090909   66.295455   84.500000
Fairy      61.529412   65.705882   48.588235
Fighting   96.777778   65.925926   66.074074
Fire       84.769231   67.769231   74.442308
Flying     78.750000   66.250000  102.500000
Ghost      73.781250   81.187500   64.343750
Grass      73.214286   70.800000   61.928571
Ground     95.750000   84.843750   63.906250
Ice        72.750000   71.416667   63.458333
Normal     73.469388   59.846939   71.551020
Poison     74.678571   68.821429   63.571429
Psychic    71.456140   67.684211   81.491228
Rock       92.863636  100.795455   55.909091
Steel      92.703704  126.370370   55.259259
Water      74.151786   72.946429   65.964286

For each generation, compute:

- count

- mean Total

- number of Legendary Pokémon (hint: use sum on Boolean)

In [99]:
df.groupby('Generation').agg(count=('Name', 'size'), mean_total=('Total', 'mean'), num_legendary=('Legendary', 'sum'))

            count  mean_total  num_legendary
Generation
1             166  426.813253              6
2             106  418.283019              5
3             160  436.225000             18
4             121  459.016529             13
5             165  434.987879             15
6              82  436.378049              8

Which type combination (Type 1 + Type 2) has the highest average Attack?

In [113]:
# put your answer here
df.groupby(['Type 1', 'Type 2'])['Attack'].mean().sort_values(ascending=False).head(1)

Type 1  Type 2
Ground  Fire      180.0
Name: Attack, dtype: float64

Which generation has the highest proportion of Legendary Pokémon?

In [107]:
df.groupby('Generation').agg(num_legendary=('Legendary', 'sum')).sort_values(by='num_legendary', ascending=False).head(1)

            num_legendary
Generation
3                      18


Which primary type has the largest variance in HP?

In [87]:
# put your answer here
df.groupby('Type 1')['HP'].var().sort_values(ascending=False).head(1)

Type 1
Normal    1312.861456
Name: HP, dtype: float64

Which primary type has the highest median Speed?

In [88]:
# put your answer here
df.groupby('Type 1')['Speed'].median().sort_values(ascending=False).head(1)

Type 1
Flying    116.0
Name: Speed, dtype: float64

Group Pokémon by whether they are Legendary or not. Compare:

- mean Total

- mean Attack

- mean Defense

- mean Speed

In [118]:
# put your answer here
df.pivot_table(index=['Legendary'], values=['Total', 'Attack', 'Defense', 'Speed'], aggfunc='mean')

               Attack    Defense       Speed       Total
Legendary
False       75.669388  71.559184   65.455782  417.213605
True       116.676923  99.661538  100.184615  637.384615

Show the top 5 strongest types by mean Total.

In [92]:
# put your answer here
df.groupby('Type 1')['Total'].mean().sort_values(ascending=False).head(5)

Type 1
Dragon     550.531250
Steel      487.703704
Flying     485.000000
Psychic    475.947368
Fire       458.076923
Name: Total, dtype: float64

Rank generations by their average Attack.

In [93]:
# put your answer here
df.groupby('Generation')['Attack'].mean().sort_values(ascending=False)

Generation
4    82.867769
5    82.066667
3    81.625000
1    76.638554
6    75.804878
2    72.028302
Name: Attack, dtype: float64

Show the top 10 fastest Pokémon using nlargest(10, "Speed").

In [117]:
# put your answer here
df.nlargest(10, 'Speed')[['Name', 'Speed']]

                          Name  Speed
431          DeoxysSpeed Forme    180
315                    Ninjask    160
71       AlakazamMega Alakazam    150
154  AerodactylMega Aerodactyl    150
428         DeoxysNormal Forme    150
429         DeoxysAttack Forme    150
19       BeedrillMega Beedrill    145
275      SceptileMega Sceptile    145
678                   Accelgor    145
109                  Electrode    140